language: php
php:
  - '7.1'

env:
  - TRAVIS_CI=1

before_script:
  - composer install
  - nvm install node
  - npm install -g gulp-cli
  - npm update

script:
  - composer test
  - composer lint
  - gulp package

cache:
  directories:
    - $HOME/.composer/cache/files
